modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT License"

[[mods]]
modId = "showhandmod"
version = "${file.jarVersion}"
displayName = "Show Hand Mod"
authors = "Yu_212"
description = '''

'''

[[dependencies.showhandmod]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.showhandmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "CLIENT"
